package kaijus.bizhacks.classifier.ui;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileSystemView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class ClassifierMenue extends javax.swing.JFrame {

	// Variables declaration - do not modify                     
	private java.awt.Choice catagory;
	private javax.swing.JButton chooseimg;
	private java.awt.TextArea description;
	private javax.swing.JLabel image;
	private javax.swing.JDesktopPane jDesktopPane1;
	private java.awt.Button reset;
	private java.awt.Button submit;
	private java.awt.TextField title;
	// End of variables declaration
	
	private BufferedImage loadedImage = null;
	//private String loadedPath = null;

	private static final long serialVersionUID = -594277375741819832L;
	
	/**
	 * Creates new form ClassifierMenue
	 */
	public ClassifierMenue() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		jDesktopPane1 = new javax.swing.JDesktopPane();
		description = new java.awt.TextArea();
		title = new java.awt.TextField();
		submit = new java.awt.Button();
		reset = new java.awt.Button();
		image = new javax.swing.JLabel("image", SwingConstants.CENTER);
		catagory = new java.awt.Choice();
		chooseimg = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		catagory.add("Computers");
		catagory.add("Mobile Phones");
		catagory.add("Cameras");
		catagory.add("Headphones");
		catagory.add("TVs");

		description.setName("description"); // NOI18N
		description.setText("Description");
		description.setRows(20);
		description.setColumns(55);
		
		title.setName("title"); // NOI18N
		title.setText("Title");
		
		submit.setActionCommand("submit");
		submit.setLabel("Submit");
		submit.setName("submit"); // NOI18N
		submit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitActionPerformed(evt);
			}
		});

		reset.setActionCommand("reset");
		reset.setLabel("Reset");
		reset.setName("Reset"); // NOI18N
		reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetActionPerformed(evt);
			}
		});

		image.setText("chooseImage");

		chooseimg.setText("Image");
		chooseimg.setActionCommand("chooseFile");
		chooseimg.setName("chooseimg"); // NOI18N
		chooseimg.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chooseimgActionPerformed(evt);
			}
		});

		jDesktopPane1.setLayer(description, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(title, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(submit, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(reset, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(image, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(catagory, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jDesktopPane1.setLayer(chooseimg, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
		jDesktopPane1.setLayout(jDesktopPane1Layout);
		jDesktopPane1Layout.setHorizontalGroup(
				jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
						.addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jDesktopPane1Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jDesktopPane1Layout.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(chooseimg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
												.addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(catagory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap())
				);
		jDesktopPane1Layout.setVerticalGroup(
				jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
						.addGap(33, 33, 33)
						.addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jDesktopPane1Layout.createSequentialGroup()
										.addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(catagory, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jDesktopPane1Layout.createSequentialGroup()
										.addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(chooseimg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
								.addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap())
				);

		submit.getAccessibleContext().setAccessibleName("Submit");
		reset.getAccessibleContext().setAccessibleName("Reset");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jDesktopPane1)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jDesktopPane1)
				);

		pack();
	}

	private void resetActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("Reset");
	}                                     

	private void submitActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("Submit");
	}                                      

	private void chooseimgActionPerformed(java.awt.event.ActionEvent evt) {      
		JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
		jfc.setDialogTitle("Choose a directory to save your file: ");
		jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
		//jfc.setFileFilter();
		jfc.setFileFilter(new FileFilter(){
			@Override
			public boolean accept(File f) {
				String name = f.getName();
				return name.endsWith(".png") || name.endsWith("jpg");
			}
			@Override
			public String getDescription() {
				return "Image File";
			}
        });

		int returnValue = jfc.showSaveDialog(null);
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			if (!jfc.getSelectedFile().isDirectory()) {
				System.out.println("You selected the file: " + jfc.getSelectedFile());
				//loadedPath = jfc.getSelectedFile().getAbsolutePath();
				try {
					loadedImage = ImageIO.read(jfc.getSelectedFile());
					ImageIcon ii = new ImageIcon(loadedImage);
					image.setIcon(ii);
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClassifierMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClassifierMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClassifierMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClassifierMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClassifierMenue().setVisible(true);
			}
		});
	}
}
